### ISSUE TITLE
HTTP request failed

### ISSUE THREAD

**Issue by ghost** [mtsmfm/vscode-k8s-quick-attach#2]
I can select context, press Enter and then I got a HTTP request failed-Error
Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by mtsmfm** [comment]
Sorry for being late reply.
If you still face the same error please reopen this issue and upload actual logs you got.
