### ISSUE TITLE
Error 'unable to verify the first certificate' occurs only when the Copilot extension is enabled.

### ISSUE THREAD

**Issue by st6446** [mtsmfm/vscode-k8s-quick-attach#4]
Hi, @mtsmfm Long time no see!

I encountered a strange issue while using Copilot. I would appreciate it if you could help me out.

-----

## steps to reproduce
1. Enable GitHub Copliot extension
2. Run Command k8s quick attach
3. Select k8s context
4. 'unable to verify the first certificate' occurs. 
<img width="492" alt="スクリーンショット 2023-11-10 13 20 08" src="https://github.com/mtsmfm/vscode-k8s-quick-attach/assets/48878902/026f2528-f149-411b-aeba-77fcf85e85a9">

I checked the error logs, including the extension host, but no relevant logs were outputted except for the one displayed on the window.

Furthermore, disabling or uninstalling the Copilot extension prevents the above error from occurring.

**Comment by mtsmfm** [comment]
Hi, thank you for reporting.
Unfortunately I can't reproduce the problem.

I can get suggestion from Copilot even on k8s env.

![image](https://github.com/mtsmfm/vscode-k8s-quick-attach/assets/1796864/874038a3-5e46-4ac9-a26e-f8a5bb82c851)

Try attaching to k8s container without this extension.

https://code.visualstudio.com/docs/devcontainers/attach-container#_attach-to-a-container-in-a-kubernetes-cluster

This extension leverages VSCode's remote feature so if you get the same result please file an issue on it https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools

**Comment by st6446** [comment]
@mtsmfm 
I have confirmed that I can attach to a Kubernetes Pod without using k8s quick attach.
<img width="304" alt="スクリーンショット 2023-11-13 11 09 43" src="https://github.com/mtsmfm/vscode-k8s-quick-attach/assets/48878902/c90ab8ef-2e1d-4ee8-b050-3ab74e261ec9">


It seems that my colleagues who are also using the same Kubernetes environment are experiencing the same issue. To determine whether the issue lies with Kubernetes itself, the Copilot extension, or the k8s quick attach tool, what should I investigate?

**Comment by mtsmfm** [comment]
> I have confirmed that I can attach to a Kubernetes Pod without using k8s quick attach.

@st6446 Does Copilot work if you connect to pod without this extension?

**Comment by st6446** [comment]
@mtsmfm Yes, it works.
<img width="544" alt="スクリーンショット 2023-11-13 13 57 39" src="https://github.com/mtsmfm/vscode-k8s-quick-attach/assets/48878902/bcd24ae8-1340-48fd-8ed7-535b171b4336">

----

I cloned the source code of k8s quick attach and debugged it, and I found that there is an error with the API request (GET some-kubernetes-host/api/v1/namespaces) to Kubernetes.
https://github.com/mtsmfm/vscode-k8s-quick-attach/blob/fd4dae17b0802d7326ae0663378085ffe05bce61/src/quickAttach.ts#L46

https://github.com/kubernetes-client/javascript/blob/d44fa64da440559b55f0b70f30271b9d3097f3d2/src/gen/api/coreV1Api.ts#L10023

<img width="1859" alt="スクリーンショット 2023-11-13 14 03 34" src="https://github.com/mtsmfm/vscode-k8s-quick-attach/assets/48878902/e70a4716-cc2f-4e35-a335-9be664989f37">

stack trace
```
'Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (node:_tls_wrap:1543:34)
at TLSSocket.emit (node:events:513:28)
at TLSSocket.emit (node:domain:489:12)
at TLSSocket._finishInit (node:_tls_wrap:962:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:746:12)
at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
```

----

I am also sharing the issue with the administrators of the Kubernetes cluster to verify if there are any issues with the cluster.

**Comment by mtsmfm** [comment]
It seems k8s client lib failed to call k8s API against your cluster so it's most likely your cluster or k8s config has a problem. I have no idea why it happens only with Copilot extension though.

**Comment by st6446** [comment]
In the end, since I couldn't pinpoint the issue, I managed to work around it by adding the following line to `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = '0';` in `~/.vscode/extensions/mtsmfm.vscode-k8s-quick-attach-0.8.0/src/out/extension.js`.

Thank you for taking the time to help me solve the problem!
